name: Publish NPM Package

on:
  push:
    branches: [publish]

permissions:
  contents: write

jobs:
  check:
    outputs:
      version: ${{ steps.version.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Github
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Get package version
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $VERSION"

      - name: Check if version tag exists
        run: |
          VERSION=${{ steps.version.outputs.version }}
          if git rev-parse "v$VERSION" >/dev/null 2>&1; then
            echo "⏭️ Skipping publish - version ${{ steps.version.outputs.version }} already exists"
            echo "To publish a new version, update the version in package.json first"
            exit 1
          else
            echo "New Version Found v$VERSION - proceeding with publish"
          fi
  log-for:
    needs: check
    steps:
      - name: log
        run: |
          echo "the version is ${{ needs.check.outputs.version }} here"
